name: Publish the Lichess API Demo app
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run prod
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - run: echo "Artifact uploaded successfully"
      - uses: actions/deploy-pages@v3
        id: deployment
      - run: echo "Deployment URL: ${{ steps.deployment.outputs.page_url }}"
