name: Publish the Lichess API Demo app
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm run prod
        run: npm run prod
      - name: configure-pages
        uses: actions/configure-pages@v4
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
      - run: echo "Artifact uploaded successfully"
      - uses: actions/deploy-pages@v3
        id: deployment